CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE OR REPLACE FUNCTION LAZY_TEXT(a VARCHAR)
RETURNS VARCHAR AS $$
BEGIN
RETURN unaccent(lower(a));
END;
$$ IMMUTABLE LANGUAGE plpgsql;